
<?php if($data) { ?>
	<?php foreach($data as $v ) {?>
			<li id="<?php echo $v['id']; ?>" class="message_box" >				<!--<span style="color:#104974;font-size:11px"><?php echo $v['id']; ?></span>-->
				<div  align="left">
					<a data-id="<?php echo $v['id']; ?>" class="show-content second" href="javascript:void(0)" id="showFullContent-<?php echo $v['id']; ?>" >							<span class="metanews middle_title"><?php //echo date("F d, Y", strtotime($v['published'])); ?></span>							<div class="img_thumb">								<?php 										$style = '';										$marginLeft = 0;										$marginTop = 0;									if($v['type'] == 'youtube-link'){										$thumbnail = $v['thumb'];										$marginLeft = 0;										$marginTop = 0;										$height = '100%';										$style="";									}else{										$thumbnail =base_url().'_assets/videos/thumb/'.$v['thumb'];										$height = 'auto';										list($width, $height, $type, $attr) = getimagesize($thumbnail);																				if($width > 100){											$marginLeft = '-'.(($width-100)/2);										}elseif($width == 100){											$marginLeft = 0;										}elseif($width < 100){											$marginLeft = ((100-$width)/2);										}																				if($height > 70){											//$marginTop = intval((($height-70)/30));											$marginTop =0;										}elseif($height == 70){											$marginTop = 0;										}elseif($height < 70){											$marginTop = intval(((70-$height)/9));										}									}											$style='height:'.$height.'; overflow:hidden !important; border-radius:0 !important;margin:auto;margin-top:'.$marginTop.'px;';															?>								<img class="thumb" style="<?php echo $style;?>" src="<?php echo $thumbnail;?> " />								<div class="play_button"></div>							</div>							<?php $countTitle = strlen($v['title']); ?>							<div class=" title title-news <?php echo ($countTitle == 0 ? 'middle_title': 'middle_pos'); ?>">								<?php echo character_limiter($v['title'], 58); ?>							</div>							<div class=" sub_title sub_title-news">								<?php echo character_limiter($v['description'], 60); ?>														</div>													</a>
				</div>
			</li>
	<?php 		$lastID = $v['id']; 	}		?>	
<?php } ?>	
